# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsum', '0002_auto_20170417_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
                ('meaning', models.TextField()),
                ('date_saved', models.DateTimeField()),
            ],
            options={
                'ordering': ('date_saved',),
            },
        ),
    ]
