# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsum', '0003_dailyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyword',
            name='date_saved',
            field=models.DateField(),
        ),
    ]
