# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsum', '0004_auto_20170424_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyword',
            old_name='meaning',
            new_name='definition',
        ),
    ]
